Repository algosup/2024-2025-project-2-serious-game-team-8, pull requests merged in 2024-12, with the labels that each got.

#32 Update technical_specifications.md
  documents/technical_specifications/technical_specifications.md
Labels: documentation

#44 Quality assurance
  documents/quality_assurance/media/Mind Map.smmx
  documents/quality_assurance/media/SimpleMind Mind Maps.sm2store
  documents/quality_assurance/test_plan.md
Labels: documentation

#45 forgot to merge documents into main :(
  documents/quality_assurance/media/Mind Map.smmx
  documents/quality_assurance/media/SimpleMind Mind Maps.sm2store
  documents/quality_assurance/test_plan.md
Labels: documentation, test

#46 fix missing dash and missing link
  documents/quality_assurance/test_plan.md
Labels: documentation, test

#63 add user manual mentions to test plan
  documents/quality_assurance/test_plan.md
Labels: documentation, enhancement
